[package]
edition = "2024"
name = "aemark"
version = "0.1.4"

[lib]
name = "aemark"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.29.2"

[dependencies.mark]
path = "mark"

[workspace]
members = [
    "mark",
    "wasm",
]
resolver = "3"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
